export enum CUSTOMER_ORDER_STATUS {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
  COMPLETED = "COMPLETED",
}

export enum CUSTOMER_ORDER_VENDOR_STATUS {
  NEW = "NEW",
  CANCELLED = "CANCELLED",
  ACCEPTED = "ACCEPTED",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
  COMPLETED = "COMPLETED",
}

export enum CUSTOMER_ORDER_VENDOR_PRODUCT_STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  CANCELLED = "CANCELLED",
}

export enum DELIVERY_ORDER_STATUS {
  NEW = "NEW",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
}

export enum DELIVERY_STATUS {
  PENDING = "PENDING",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
}
